# Generated by Django 4.1.3 on 2022-11-29 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripcion'),
        ),
    ]
