# Generated by Django 4.1.3 on 2022-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_categoria_post_categoria_post_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
